# Generated by Django 5.0 on 2023-12-27 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_topic_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
    ]
